### ISSUE TITLE
公式编号样式需更新：(1-1)变为(1.1)

### ISSUE THREAD

**Issue by incoincoin** [Ginufet/tongji-dissertation-master-template#1]
[同济大学学位论文写作规范](https://gs.tongji.edu.cn/info/1063/1754.htm)已更新，章节号与公式编号之间由“-”变为“.”。

(【参阅】同济大学研究生学位论文写作规范（试行）（2021）)

**Comment by Ginufet** [comment]
感谢指正，已更新。
